/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 dog.glb --types --shadows 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

const ModelPath = "/assets/dog.glb";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
  };
  materials: {
    brown: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    pink: THREE.MeshStandardMaterial;
  };
  // animations: GLTFAction[]
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Dog(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(ModelPath) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.brown}
        scale={[1.065, 1.59, 0.578]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.white}
        position={[0, 0.616, 0.421]}
        scale={[1, 0.335, 0.561]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.black}
        position={[0, 0.703, 0.807]}
        scale={[0.168, 0.101, 0.263]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.black}
        position={[-0.515, 1.199, 0.541]}
        scale={[0.228, 0.075, 0.068]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.black}
        position={[0.524, 1.199, 0.541]}
        scale={[0.228, 0.075, 0.068]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.white}
        position={[-0.159, 1.37, 0.541]}
        scale={[0.087, 0.075, 0.068]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.white}
        position={[0.174, 1.37, 0.541]}
        scale={[0.087, 0.075, 0.068]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.brown}
        position={[-0.515, 1.728, 0.265]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.382, 0.157, 0.382]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.pink}
        position={[-0.515, 1.728, 0.332]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.313, 0.129, 0.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.brown}
        position={[0.546, 1.728, 0.265]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.382, 0.157, 0.382]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.pink}
        position={[0.546, 1.728, 0.332]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.313, 0.129, 0.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.brown}
        position={[-0.515, -1.683, 0.051]}
        scale={[0.287, 0.421, 0.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials.brown}
        position={[0.524, -1.683, 0.051]}
        rotation={[-0.313, -0.096, 0.288]}
        scale={[0.287, 0.421, 0.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials.brown}
        position={[-1.231, -0.044, 0.051]}
        rotation={[0, 0, -2.035]}
        scale={[0.287, 0.421, 0.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials.brown}
        position={[1.237, -0.345, 0.051]}
        rotation={[0, 0, 1.003]}
        scale={[0.287, 0.421, 0.304]}
      />
    </group>
  );
}

useGLTF.preload(ModelPath);
